import SectionTitle from "components/section-title";
import Widget from "components/widget";

const Index: React.FC = () => (
    <>
      <SectionTitle title="" subtitle="Privacy policy" />
      <Widget
          title="Privacy policy"
          description={
            <span>
          Generated by{" "}
              <a
                  className="text-blue-500"
                  href="https://getterms.io/"
                  target="_blank"
                  rel="noopener noreferrer">
            GetTerms.io
          </a>
        </span>
          }>
        <div className="prose prose-sm max-w-none text-gray-900 dark:text-white">
          <p>
          At our crowdfunding platform, we take your privacy seriously. This Privacy Policy explains how we collect, use, and protect your personal information. By using our platform, you agree to the collection and use of information in accordance with this policy.
          </p>
          <h6 className="font-bold">1. Information We Collect</h6>
          <p>
          We may collect personal information such as your name, email address, and payment information when you create an account on our platform, make a donation or start a campaign. We may also collect non-personal information such as your IP address and browser type. We only collect information that is necessary for the purpose of providing our services to you.
          </p>
          <h6 className="font-bold">2. How We Use Your Information</h6>
          <p>
          We use your personal information to provide our services to you, process your donations, and communicate with you about your account or campaigns. We may also use your information to improve our platform, prevent fraud, and comply with legal obligations.
          </p>
          <h6 className="font-bold">3. How We Protect Your Information</h6>
          <p>
          We take commercially reasonable measures to protect your personal information from loss, theft, and unauthorized access, disclosure, copying, use, or modification. We use secure servers and encryption technology to protect your information. However, no method of transmission over the Internet or electronic storage is 100% secure, and we cannot guarantee absolute security.
          </p>
          <h6 className="font-bold">4. Information Sharing</h6>
          <p>
          We do not share your personal information with third parties except when required by law or with your consent. We may share your information with service providers who help us provide our services to you, such as payment processors and email service providers. These service providers are authorized to use your information only as necessary to provide the services to us.
          </p>
          <h6 className="font-bold">5. External Links</h6>
          <p>
          Our platform may contain links to external websites that are not operated by us. We have no control over the content and practices of these websites and are not responsible for their privacy policies or practices. We encourage you to review the privacy policies of these websites before providing them with any personal information.
          </p>
          <h6 className="font-bold">6. Your Choices</h6>
          <p>
          You have the right to access, correct, and delete your personal information. You can do this by logging into your account or contacting us. You may also choose to opt-out of receiving marketing communications from us by following the instructions in the communication.
          </p>
          <h6 className="font-bold">7. Changes to This Privacy Policy</h6>
          <p>
          We may update this Privacy Policy from time to time by posting a new version on our platform. We will notify you of any changes by email or by posting a notice on our platform. Your continued use of our platform after any changes to this Privacy Policy constitutes your acceptance of the new terms.
          </p>          
          <p>This policy is effective as of 1 February 2023.</p>
        </div>
      </Widget>
    </>
);
export default Index;
